world: "rmuc_2024"

robots:
  rmuc_2024:
    - name: "scorpio"
      x_pose: "6.35"
      y_pose: "7.6"
      z_pose: "0.2"
      yaw: "0.0"

  rmuc_2025:
    - name: "scorpio"
      x_pose: "3.4"
      y_pose: "9.5"
      z_pose: "0.28"
      yaw: "0.0"

  turtlebot3_dqn:
    - name: "scorpio"
      x_pose: "0.0"
      y_pose: "0.0"
      z_pose: "0.0"
      yaw: "0.0"

  turtlebot3_house:
    - name: "scorpio"
      x_pose: "-2.0"
      y_pose: "1.0"
      z_pose: "0.0"
      yaw: "0.0"

  warehouse:
    - name: "scorpio"
      x_pose: "0.0"
      y_pose: "0.0"
      z_pose: "0.0"
      yaw: "0.0"

  simple_baylands:
    - name: "scorpio"
      x_pose: "2.7185"
      y_pose: "1"
      z_pose: "0.0"
      yaw: "-1.4112"
